FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl
RUN apt-get install -y default-libmysqlclient-dev build-essential python3-dev
RUN apt-get install -y pkg-config


WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY .env /app/

COPY ./backend /app/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]