FROM python:3.10-slim

WORKDIR /app

# RUN apt-get update
# RUN apt-get install -y pkg-config

COPY requirements-worker.txt /app/
RUN pip install --no-cache-dir -r requirements-worker.txt

COPY .env /app/

COPY worker.py /app/

CMD ["python","worker.py"]



